/*
 The MIT License, Copyright (c) 2011 Jordan Santell
 @author jsantell@gmail.com (Jordan Santell)
*/
var Unburyme=Unburyme||{};Unburyme.Config=function(){this.slideSpeed=500;this.sliderWaitToCalculate=50;this.sliderMax=5E3;this.fadeSpeed=200;this.colorSet=["#01dcff","#85f9a1","#e7f985","#ff9ed7","#9ec3ff"];$.fx.off=!1};Unburyme.debug=function(a){typeof console=="object"&&console.log(a)};Unburyme.Date=function(){this.month=this.year=0;this.setCurrent()};Unburyme.Date.prototype.setCurrent=function(){var a=new Date;this.year=a.getFullYear();this.month=a.getMonth()};Unburyme.Date.prototype.setDate=function(a,b){this.year=a;this.month=b};Unburyme.Date.prototype.getMonth=function(){return this.month};Unburyme.Date.prototype.getYear=function(){return this.year};Unburyme.Date.prototype.getFloat=function(){return parseFloat(this.year+this.month*0.01)};
Unburyme.Date.prototype.getLatest=function(a){var b=new Unburyme.Date;this.getYear()>a.getYear()?b.setDate(this.getYear(),this.getMonth()):this.getYear()<a.getYear()?b.setDate(a.getYear(),a.getMonth()):this.getMonth()>a.getMonth()?b.setDate(this.getYear(),this.getMonth()):this.getMonth()<a.getMonth()?b.setDate(a.getYear(),a.getMonth()):b.setDate(this.getYear(),this.getMonth());return b};Unburyme.Date.prototype.increment=function(){this.month==11?(this.year++,this.month=0):this.month++};
Unburyme.Date.prototype.print=function(){return["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"][this.month]+" "+this.year};Unburyme.Graph=function(a){this.loanApp=a;this.loanDataSet=[];this.loanData=[];this.loanNames=[];this.dateSet=[];this.colorSet=this.loanApp.config.colorSet;this.lastFieldGraphed="princRemaining"};
Unburyme.Graph.prototype.draw=function(a){if(!a)a=this.lastFieldGraphed;$("#graph").fadeIn(this.loanApp.config.fadeSpeed);$("#graphViewOptions").fadeIn(this.loanApp.config.fadeSpeed);this.drawTitle(a);this.getGraphData(a);this.makeDataSet();this.makeXAxis();this.lastFieldGraphed=a;$.plot($("#graph"),this.loanDataSet,{colors:this.colorSet,xaxis:{ticks:this.dateSet},yaxis:{tickFormatter:this.dollarFormatter},grid:{backgroundColor:{colors:["#ffffff","#b0edf7"]}}})};
Unburyme.Graph.prototype.drawTitle=function(a){var b="";$("#graphTitle").fadeIn(this.loanApp.config.fadeSpeed);switch(a){case "princRemaining":b="Principle Remaining";break;case "princPaid":b="Principle Paid";break;case "totalInterestPaid":b="Total Interest Paid";break;case "monthlyPayment":b="Monthly Payment"}$("#graphTitle").html(b)};Unburyme.Graph.prototype.makeDataSet=function(){for(var a=0;a<this.loanApp.loanCount;a++){var b=[];b.label=this.loanNames[a];b.data=this.loanData[a];this.loanDataSet.push(b)}};
Unburyme.Graph.prototype.makeXAxis=function(){var a=new Unburyme.Date,b=a.getMonth(),d=a.getYear()+1,f=1,h=1,b=(12-b)%12,e=0;a.setCurrent();for(a=0;a<this.loanApp.initLoanCount();a++)if(this.loanData[a].length>e)e=this.loanData[a].length;e=Math.ceil(e/12);e>8&&(f=Math.ceil(e/8),h=Math.ceil(e/8));for(a=0;a<e;a++){var g=[];g.push(b);g.push(d+a*h);this.dateSet.push(g);b+=12*f}};
Unburyme.Graph.prototype.getGraphData=function(a){this.clearGraphData();for(var b=0;b<this.loanApp.initLoanCount();b++)this.loanData.push(this.loanApp.initLoanArray[b].results.getGraphData(a)),this.loanNames.push(this.loanApp.initLoanArray[b].getName())};Unburyme.Graph.prototype.clearGraphData=function(){this.loanDataSet=[];this.loanNames=[];this.loanData=[];this.dateSet=[]};Unburyme.Graph.prototype.dollarFormatter=function(a){return"$"+a};
Unburyme.Graph.prototype.reset=function(){$("#graph").fadeOut(this.loanApp.config.fadeSpeed);$("#graphViewOptions").fadeOut(this.loanApp.config.fadeSpeed);$("#graphTitle").fadeOut(this.loanApp.config.fadeSpeed);this.clearGraphData();this.lastFieldGraphed="princRemaining"};$(function(){var a=new Unburyme.LoanApp;a.createLoan();$("#email").html("<a href='mailto:jsantell@gmail.com' title='email Jordan Santell'>jsantell@gmail.com</a>");$(".paymentTypeButtonLink").click(function(){$(this).is(".avaLink")?($("#avalanche").removeClass("unselectedPaymentType").addClass("selectedPaymentType"),$("#snowball").removeClass("selectedPaymentType").addClass("unselectedPaymentType"),a.paymentType="avalanche"):($("#snowball").removeClass("unselectedPaymentType").addClass("selectedPaymentType"),
$("#avalanche").removeClass("selectedPaymentType").addClass("unselectedPaymentType"),a.paymentType="snowball");f()});$(".createLoanPlus").live("click",function(){a.createLoan()});$(".destroyLoan").live("click",function(){var b=$(this).attr("id").substr(6);a.destroyLoan(b);f()});$("#paymentSlider").slider({value:100,min:0,max:5E3,animate:!0,slide:function(b,g){$("#totalMonthlyPayment").val(logPositionToPayment(g.value));a.updatePayment(logPositionToPayment(g.value));d(logPositionToPayment(g.value))}});
var b=null,d=function(e){b&&clearTimeout(b);b=setTimeout(function(){a.autoCalc&&$("input.uninitialized").addClass("invalidField");logPositionToPayment(e)<a.totalMinPayment&&$("#paymentSlider").slider("option","value",logPaymentToPosition(a.totalMinPayment));f()},a.config.sliderWaitToCalculate)};logPaymentToPosition=function(a){return a};logPositionToPayment=function(a){return a};$(".resultsContainer").live("click",function(){var b=$(this).attr("id").substr(16);a.getLoan(b).results.click()});$(".graphView").click(function(){$(this).attr("id")==
"graph_princRemaining"?a.graph.draw("princRemaining"):$(this).attr("id")=="graph_princPaid"?a.graph.draw("princPaid"):$(this).attr("id")=="graph_totalInterestPaid"?a.graph.draw("totalInterestPaid"):$(this).attr("id")=="graph_monthlyPayment"&&a.graph.draw("monthlyPayment")});$("#totalMonthlyPayment").live("change",function(){var b=$(this).val();a.validatePayment(b)&&(a.updatePayment(b),$("#paymentSlider").slider("option","value",logPaymentToPosition(b)),f())});$("#loanBarInputContainer input").live("change",
function(){var b,d,j=$(this).val();$(this).hasClass("name")?(b=$(this).attr("id").substr(8),d="name"):$(this).hasClass("balance")?(b=$(this).attr("id").substr(11),d="balance"):$(this).hasClass("minPayment")?(b=$(this).attr("id").substr(14),d="minPayment"):$(this).hasClass("interest")&&(b=$(this).attr("id").substr(12),d="interest");a.getLoan(b).validate(d,j)&&(a.updateLoan(b,d,h(j)),d=="minPayment"&&$("#paymentSlider").slider("option","value",logPaymentToPosition(a.totalPayment)));var k=b;d=="name"&&
(j==""?(j="Loan "+(parseInt(k)+1),$("#loan"+d+k).val(j),$("#loan"+d+k).css("color","#cccccc")):$("#loan"+d+k).css("color","#444444"),a.updateLoan(k,d,j));a.getLoan(b).isInitialized.loan&&a.autoCalc&&($("input.uninitialized").addClass("invalidField"),f())});var f=function(b){if(b||a.autoCalc)$("input").hasClass("invalidField"),a.calculatePrep()},h=function(a){a=a.replace(" ","");a=a.replace(",","");return a=parseFloat(a)};$(".calculate").click(function(){$("input").hasClass("uninitialized")?$("input.uninitialized").addClass("invalidField"):
f(1)});$(".link").click(function(){$(this).attr("id")=="link_help"?($("#help").show(),$("#about").hide(),$("#feedback").hide()):$(this).attr("id")=="link_about"?($("#help").hide(),$("#about").show(),$("#feedback").hide()):$(this).attr("id")=="link_feedback"&&($("#help").hide(),$("#about").hide(),$("#feedback").show())});$("body").click(function(a){$(a.target).hasClass("link")||$(".moreInfo").hide()});$(".help").mouseover(function(a){var b=a.pageX+30,a=a.pageY-20;$("#helpPopup").css({left:b+"px",top:a+
"px"});$(this).attr("id")=="totalMonthlyPaymentHelp"?$("#help_tmp").show():$(this).attr("id")=="paymentTypeHelp"&&$("#help_pt").show()});$(".help").mouseout(function(){$(this).attr("id")=="totalMonthlyPaymentHelp"?$("#help_tmp").hide():$(this).attr("id")=="paymentTypeHelp"&&$("#help_pt").hide()})});Number.prototype.log2=function(){return Math.log(this)/Math.LN2};if(!Array.indexOf)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1};Unburyme.LoanApp=function(){this.config=new Unburyme.Config;this.loanArray=[];this.initLoanArray=[];this.uidIterator=this.loanCount=0;this.paymentType="avalanche";this.validPayment=this.totalMinPayment=this.totalPayment=0;this.possibleCalc=1;this.errorTimeout=this.autoCalc=0;this.rollover=this.extraPayment=null;this.rolloverMonth=new Unburyme.Date;this.graph=new Unburyme.Graph(this);this.totalResults=new Unburyme.TotalResults(this)};
Unburyme.LoanApp.prototype.getLoan=function(a){for(var b=-1,d=0;d<this.loanCount;d++)this.loanArray[d].uid==a&&(b=d);return this.loanArray[b]};Unburyme.LoanApp.prototype.getLoanIndex=function(a){for(var b=-1,d=0;d<this.loanCount;d++)this.loanArray[d].uid==a&&(b=d);return b};Unburyme.LoanApp.prototype.createLoan=function(){this.loanArray.push(new Unburyme.Loan(this.uidIterator,this));this.loanCount++;this.uidIterator++};
Unburyme.LoanApp.prototype.destroyLoan=function(a){this.getLoan(a).destroy();this.loanArray.splice(this.getLoanIndex(a),1);this.loanCount--;this.refreshInitLoanArray();this.autoCalc==1&&this.initLoanCount()==0&&this.clearData()};Unburyme.LoanApp.prototype.updateLoan=function(a,b,d){switch(b){case "name":this.getLoan(a).setName(d);break;case "balance":this.getLoan(a).setBalance(d);break;case "minPayment":this.getLoan(a).setMinPayment(d);this.updateTotalMinPayment();break;case "interest":this.getLoan(a).setInterest(d)}this.refreshInitLoanArray()};
Unburyme.LoanApp.prototype.updateTotalMinPayment=function(){for(var a=0,b=0;b<this.loanCount;b++)a+=this.loanArray[b].getMinPayment();this.totalMinPayment=a;if(this.totalMinPayment>this.totalPayment)this.totalPayment=this.totalMinPayment,$("#totalMonthlyPayment").val(this.totalPayment),$("#totalMonthlyPayment").removeClass("invalidField"),this.validPayment=!0};Unburyme.LoanApp.prototype.updatePayment=function(a){this.totalPayment=a;this.updateTotalMinPayment();this.validPayment=!0;this.validatePaymentDisplay(!0)};
Unburyme.LoanApp.prototype.validatePayment=function(a){var b=!0,d=null;for(i=0;i<a.length&&b==!0;i++)d=a.charAt(i),"0123456789., ".indexOf(d)==-1&&(b=!1);a==""&&(b=!1);this.validatePaymentDisplay(b);this.validPayment=b?!0:!1;return b};Unburyme.LoanApp.prototype.validatePaymentDisplay=function(a){a?$("#totalMonthlyPayment").removeClass("invalidField"):$("#totalMonthlyPayment").addClass("invalidField")};Unburyme.LoanApp.prototype.isPaymentValid=function(){return this.validPayment};
Unburyme.LoanApp.prototype.getInfo=function(a,b){switch(b){case "name":return this.getLoan(a).getName();case "balance":return this.getLoan(a).getBalance();case "minPayment":return this.getLoan(a).getMinPayment();case "interest":return this.getLoan(a).getInterest()}};
Unburyme.LoanApp.prototype.calculatePrep=function(){if(this.areLoansValid()&&this.isPaymentValid()){$("#totalMonthlyPayment").val();var a=this.sortLoans();this.extraPayment=this.totalPayment-this.totalMinPayment;this.rollover=0;this.rolloverMonth=new Unburyme.Date;this.possibleCalc=!0;this.calculate(a);if(this.possibleCalc==!0)this.graph.draw(),this.totalResults.calculate(),this.autoCalc||$(".calculate").fadeOut(Unburyme.Config.fadeSpeed),this.autoCalc=1}};
Unburyme.LoanApp.prototype.calculate=function(a){for(var b=new Unburyme.Date,d=[],f=[],h=[],e=[],g=[],j=[],k=[],m=this.initLoanCount(),n=0,c=0;c<this.initLoanCount();c++)a[c].results.totalInterestPaid=0,a[c].results.drawStart(),a[c].getName(),d[c]=a[c].getBalance(),f[c]=a[c].getInterest()*0.01,h[c]=a[c].getMinPayment(),k[c]=0;for(;m&&this.possibleCalc;){for(var l=this.totalPayment,o=!0,c=0;c<this.initLoanCount();c++)k[c]==0&&(e[c]=d[c]*(f[c]/12),g[c]=0,a[c].results.totalInterestPaid+=e[c],j[c]=h[c],
l-=h[c]);for(;(l>0||o)&&m;){for(c=0;c<this.initLoanCount();c++)l>0&&d[c]>0&&(j[c]+=l,l=0);for(c=0;c<this.initLoanCount();c++)d[c]>0&&(j[c]-e[c]<d[c]?(g[c]=j[c]-e[c],d[c]-=g[c]):(g[c]=d[c],l=j[c]-d[c]-e[c],j[c]=d[c]+e[c],d[c]=0,m-=1,a[c].results.payOffDate.setDate(b.getYear(),b.getMonth())));o=!1}for(c=0;c<this.initLoanCount();c++)k[c]==0&&(d[c]==0&&(k[c]=1),a[c].results.drawMain(n,b,j[c],g[c],e[c],d[c]));b.increment();n++;if(b.getYear()>2200)this.possibleCalc=!1}if(this.possibleCalc){for(c=0;c<this.initLoanCount();c++)a[c].results.drawFinal();
for(b=0;b<this.initLoanCount();b++)b==0?$("#allResultsContainer").prepend($("#resultsContainer"+a[b].getUID())):$("#resultsContainer"+a[b].getUID()).insertAfter($("#resultsContainer"+a[b-1].getUID()))}else this.impossibleCalcDisplay()};
Unburyme.LoanApp.prototype.sortLoans=function(){for(var a=[],b=[],d="",d=this.paymentType=="avalanche"?"interest":"balance";a.length<this.loanCount;){for(var f=0,h=0,e=0;e<this.initLoanCount();e++){var g=this.initLoanArray[e].uid;b.indexOf(g)==-1&&this.getInfo(g,d)>f&&(h=g,f=this.getInfo(g,d))}b.push(h);a.push(this.getLoan(h))}return this.paymentType=="avalanche"?a:a.reverse()};Unburyme.LoanApp.prototype.initLoanCount=function(){return this.initLoanArray.length};
Unburyme.LoanApp.prototype.refreshInitLoanArray=function(){this.initLoanArray=[];for(var a=0;a<this.loanCount;a++)this.loanArray[a].isInitialized.loan&&!this.loanArray[a].deleted&&this.initLoanArray.push(this.loanArray[a])};Unburyme.LoanApp.prototype.clearData=function(){this.autoCalc=0;this.rolloverMonth.setCurrent();this.graph.reset();this.totalResults.reset();this.refreshInitLoanArray();$(".calculate").fadeIn(Unburyme.Config.fadeSpeed);this.createLoan()};
Unburyme.LoanApp.prototype.impossibleCalcDisplay=function(){var a=this.config.slideSpeed;if($("#error").length==0){var b="<div id='error'>\n";b+="    <p>One or more of the current loans will take <strong>centuries</strong> to pay off.</p>";b+="    <p>Please use more reasonable loan information.</p>";b+="</div>";$("#enclosure").prepend(b);$("#error").css("display","none")}$("#error").slideDown(this.config.slideSpeed);this.errorTimeout&&window.clearTimeout(this.errorTimeout);this.errorTimeout=window.setTimeout(function(){$("#error").slideUp(a)},
3E3)};Unburyme.LoanApp.prototype.areLoansValid=function(){for(var a=!0,b=0;b<this.loanCount;b++)this.loanArray[b].isValid.loan||(a=!1);return a};Unburyme.Loan=function(a,b){this.uid=a;this.loanApp=b;this.name="Loan "+(this.uid+1);this.interest=this.minPayment=this.balance=0;this.results=new Unburyme.ResultBar(this.uid,this,this.loanApp);this.create();this.isInitialized={loan:0,name:0,balance:0,minPayment:0,interest:0};this.isValid={loan:0,name:0,balance:0,minPayment:0,interest:0};this.deleted=0};
Unburyme.Loan.prototype.create=function(){var a="<div id='loanbar"+this.uid+"' class='loanBarInput uninitialized'>\n";a+="   <a href='#' class='destroyLoan' id='delete"+this.uid+"'><div class='destroyLoanX'></div></a>\n";a+="   <div class='loanName'>\n";a+="                   <div class='fieldTitle'>Loan Name</div>\n";a+="                   <div class='fieldInput'><input id='loanname"+this.uid+"' class='name' /></div>\n";a+="           </div>\n";a+="   <div class='currentBalance'>\n";a+="                   <div class='fieldTitle'>Current Balance</div>\n";
a+="                   <div class='fieldInput'>$<input id='loanbalance"+this.uid+"' class='balance  uninitialized' /></div>\n";a+="           </div>\n";a+="           <div class='minMonthlyPayment'>\n";a+="                   <div class='fieldTitle'>Min. Payment</div>\n";a+="                   <div class='fieldInput'>$<input id='loanminPayment"+this.uid+"' class='minPayment  uninitialized' /></div>\n";a+="           </div>\n";a+="           <div class='interest'>\n";a+="                   <div class='fieldTitle'>Interest</div>\n";
a+="                   <div class='fieldInput'>%<input id='loaninterest"+this.uid+"' class='interest  uninitialized' /></div>\n";a+="        </div>\n";a+="       </div>\n";$("#loanBarInputContainer").append(a);$("#loanbar"+this.uid).css("display","none").slideDown(this.loanApp.config.slideSpeed)};
Unburyme.Loan.prototype.destroy=function(){$("#loanbar"+this.uid).slideUp(this.loanApp.config.slideSpeed,function(){$("#loanbar"+this.uid).remove()});this.results.destroy();this.cleanField("bar");this.cleanField("name");this.cleanField("balance");this.cleanField("minPayment");this.cleanField("interest");this.deleted=1;for(var a=0;a<5;a++)this.isInitialized[a]=0};Unburyme.Loan.prototype.setName=function(a){this.name=a};
Unburyme.Loan.prototype.setBalance=function(a){this.initializeField("balance");this.balance=a};Unburyme.Loan.prototype.setMinPayment=function(a){this.initializeField("minPayment");this.minPayment=a};Unburyme.Loan.prototype.setInterest=function(a){this.initializeField("interest");this.interest=a};Unburyme.Loan.prototype.getName=function(){return this.name};Unburyme.Loan.prototype.getBalance=function(){return this.balance};Unburyme.Loan.prototype.getMinPayment=function(){return this.minPayment};
Unburyme.Loan.prototype.getInterest=function(){return this.interest};Unburyme.Loan.prototype.getValue=function(a){var b="";switch(a){case "name":b=this.getName();break;case "balance":b=this.getBalance();break;case "minPayment":b=this.getMinPayment();break;case "interest":b=this.getInterest()}return b};Unburyme.Loan.prototype.getUID=function(){return this.uid};Unburyme.Loan.prototype.calculate=function(){this.results.calculate()};
Unburyme.Loan.prototype.validate=function(a,b){var d=!0,f;for(i=0;i<b.length&&d==!0;i++)f=b.charAt(i),"0123456789., ".indexOf(f)==-1&&(d=!1);b==""&&(d=!1,$("input ."+a).val(""));a=="name"&&(d=!0);this.isValid[a]=d?1:0;this.isValid.balance&&this.isValid.minPayment&&this.isValid.interest&&(this.isValid.loan=1);this.validateDisplay(a,d);return d};Unburyme.Loan.prototype.validateDisplay=function(a,b){b?$("#loan"+a+this.uid).removeClass("invalidField"):$("#loan"+a+this.uid).addClass("invalidField")};
Unburyme.Loan.prototype.cleanField=function(a){a=="loan"&&(a="bar");$("#loan"+a+this.uid).removeClass("uninitialized");$("#loan"+a+this.uid).removeClass("invalidField")};Unburyme.Loan.prototype.initializeField=function(a){this.isInitialized[a]=1;this.cleanField(a);if(this.isInitialized.balance&&this.isInitialized.minPayment&&this.isInitialized.interest)this.isInitialized.loan=1,this.cleanField("loan")};Unburyme.ResultBar=function(a,b,d){this.uid=a;this.loan=b;this.loanApp=d;this.totalInterestPaid=0;this.payOffDate=new Unburyme.Date;this.graph=this.loanApp.graph;this.graphData_princData=[];this.graphData_princPaid=[];this.graphData_totalInterestPaid=[];this.graphData_monthlyPayment=[];this.htmlMonthly=this.htmlMain=""};Unburyme.ResultBar.prototype.destroy=function(){$("#resultsContainer"+this.uid).slideUp(this.loanApp.config.slideSpeed,function(){$("#resultsContainer"+this.uid).remove()})};
Unburyme.ResultBar.prototype.drawStart=function(){this.clearGraphData();this.totalInterestPaid=0;this.htmlMonthly="<div class='monthlyResults' id='monthlyResults"+this.uid+"'>\n";this.htmlMonthly+="<table><tr>";this.htmlMonthly+="<td class='tHead month'>Month</td>\n";this.htmlMonthly+="<td class='tHead monthlyPayment'>Payment</td>\n";this.htmlMonthly+="<td class='tHead princPaid'>princPaid</td>\n";this.htmlMonthly+="<td class='tHead interestPaid'>interestPaid</td>\n";this.htmlMonthly+="<td class='tHead principle'>Principle</td>\n";
this.htmlMonthly+="<td class='tHead totalInterest'>Total Interest</td>\n";this.htmlMonthly+="</tr>\n"};
Unburyme.ResultBar.prototype.drawMain=function(a,b,d,f,h,e){this.htmlMonthly+="<tr class='alternateRows"+b.getMonth()%2+"'>\n";this.htmlMonthly+="   <td class='tBody month'>"+b.print()+"</td>\n";this.htmlMonthly+="   <td class='tBody monthlyPayment'>$"+d.toFixed(2)+"</td>\n";this.htmlMonthly+="   <td class='tBody princPaid'>$"+f.toFixed(2)+"</td>\n";this.htmlMonthly+="   <td class='tBody interestPaid'>$"+h.toFixed(2)+"</td>\n";this.htmlMonthly+="   <td class='tBody princRemaining'>$"+e.toFixed(2)+
"</td>\n";this.htmlMonthly+="   <td class='tBody totalInterestPaid'>$"+this.totalInterestPaid.toFixed(2)+"</td>\n";this.htmlMonthly+="</tr>\n";this.graphData_princRemaining.push([a,e.toFixed(2)]);this.graphData_princPaid.push([a,f.toFixed(2)]);this.graphData_totalInterestPaid.push([a,this.totalInterestPaid.toFixed(2)]);this.graphData_monthlyPayment.push([a,d.toFixed(2)])};
Unburyme.ResultBar.prototype.drawFinal=function(){this.htmlMonthly+="</table></div>";this.htmlMain="       <a class='resultBarLink' ><div class='resultBar' id='resultBar"+this.uid+"'>\n";this.htmlMain+="      <div class='loanName'>"+this.loan.getName()+"</div>\n";this.htmlMain+="      <div class='payoffDateText'>paid off by</div><div class='payoffDate'>"+this.payOffDate.print()+"</div>\n";this.htmlMain+="      <div class='totalInterestText'>total interest paid</div><div class='totalInterest'>$"+this.totalInterestPaid.toFixed(2)+
"</div>\n";this.htmlMain+="      <div class='resultBarDetailsClick'>click for details</div>";this.htmlMain+="  </div>\n";this.htmlMain+=this.htmlMonthly;this.htmlMain+="</a>\n";$("#resultBar"+this.uid).length?$("#resultsContainer"+this.uid).html(this.htmlMain):(this.htmlMain="<div class='resultsContainer' id='resultsContainer"+this.uid+"'>\n"+this.htmlMain+"</div>\n",$("#allResultsContainer").append(this.htmlMain).fadeIn(this.loanApp.config.fadeSpeed));$("#monthlyResults"+this.uid).css("display",
"none")};Unburyme.ResultBar.prototype.clearGraphData=function(){this.graphData_princRemaining=[];this.graphData_princPaid=[];this.graphData_totalInterestPaid=[];this.graphData_monthlyPayment=[]};Unburyme.ResultBar.prototype.getGraphData=function(a){var b;switch(a){case "princRemaining":b=this.graphData_princRemaining;break;case "princPaid":b=this.graphData_princPaid;break;case "totalInterestPaid":b=this.graphData_totalInterestPaid;break;case "monthlyPayment":b=this.graphData_monthlyPayment}return b};
Unburyme.ResultBar.prototype.click=function(){$("#monthlyResults"+this.uid).css("display")=="none"?$("#monthlyResults"+this.uid).slideDown(this.loanApp.config.slideSpeed):$("#monthlyResults"+this.uid).slideUp(this.loanApp.config.slideSpeed)};Unburyme.TotalResults=function(a){this.loanApp=a;this.finalPayOffDate=new Unburyme.Date;this.totalInterest=0};Unburyme.TotalResults.prototype.calculate=function(){this.clearData();for(var a=0;a<this.loanApp.initLoanCount();a++)this.finalPayOffDate=this.finalPayOffDate.getLatest(this.loanApp.loanArray[a].results.payOffDate),this.totalInterest+=this.loanApp.loanArray[a].results.totalInterestPaid;this.draw()};
Unburyme.TotalResults.prototype.draw=function(){var a='<div id="totalResultsBar">';a+='   <div class="name">Loan Total</div>\n';a+='   <div class="payoffDateText">debt free by</div><div class="payoffDate">'+this.finalPayOffDate.print()+"</div>\n";a+='   <div class="totalInterestText">total interest paid</div><div class="totalInterest">$'+this.totalInterest.toFixed(2)+"</div>\n";a+="</div>\n";$("#totalResultsContainer").fadeIn(this.loanApp.config.fadeSpeed);$("#totalResultsContainer").html(a)};
Unburyme.TotalResults.prototype.clearData=function(){this.finalPayOffDate.setCurrent();this.totalInterest=0};Unburyme.TotalResults.prototype.reset=function(){this.clearData();$("#totalResultsContainer").fadeOut(this.loanApp.config.fadeSpeed)};
